CONFIG_DIR = 'config'
CONFIG_FILE = '/'.join([CONFIG_DIR, 'example.json'])  # CUSTOMIZE
DATA = 'DATA'
DATASET = '/'.join([DATA, 'waseem_0.tsv'])  # CUSTOMIZE
ORG = '/'.join([DATA, 'org.tsv'])  # CUSTOMIZE
CACHE_DIR = 'CACHE'
LEXICON = '/'.join([DATA, 'hurtlex_EN_1.2.tsv'])
KENNEDY_RACISM_MODEL_PATH = 'models/racism.bin'
KENNEDY_SEXISM_MODEL_PATH = 'models/sexism.bin'